### ISSUE TITLE
Expand Upload File Types

### ISSUE THREAD

**Issue by AdeDoyle** [TeangaNLP/cardamom-workbench#13]
Currently uploaded files can only be raw text files (.txt and possibly .docx). In order to work with UD corpora, it will be necessary to allow users to upload CoNLL-U files, and it may be necessary to support the JSON format currently used by the Wb. glosses website backend.

**Comment by berstearns** [comment]
FOCUS in processing upload CoNLL-U files

**Comment by AdeDoyle** [comment]
Working on JSON format of Wb. website file.

**Comment by AdeDoyle** [comment]
Closing this issue. JSON format of Wb. website file was deemed to be unfeasible to represent. It is possibly unnecessary now anyhow as a result of John's recently discussed work on teanga-converters for one-off file-types.

**Comment by AdeDoyle** [comment]
Close
